nelmio_api_doc:
    documentation:
        info:
            title: DEPT Test
            description: API DOC for movies trailers using TMDB and Vimeo APIs.
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc)

